const placeTypes = [
  "amusement park",
  "aquarium",
  "art gallery",
  "bakery",
  "bar",
  "beauty salon",
  "bowling alley",
  "cafe",
  "campground",
  "casino",
  "church",
  "convenience store",
  "library",
  "lodging",
  "meal takeaway",
  "movie theater",
  "museum",
  "night club",
  "park",
  "parking",
  "restaurant",
  "shopping mall",
  "spa",
  "stadium",
  "store",
  "synagogue",
  "tourist attraction",
  "university",
  "zoo",
];

export default placeTypes;
